---

# vim:set ts=2 sw=2 et ai:

resources:

- name: bosh-repo

  type: git

  source:

    uri: https://github.com/cloudfoundry/bosh/

- name: stemcell-build

  type: git

  source:

   uri: https://github.com/fredga/Stemcell-build.git


jobs:

- name: build-stemcell

  plan:

  - get: bosh-repo

  - get: stemcell-build

  - task: build-stemcell

    config:

      platform: linux

      image_resource:

        type: docker-image

        source: { repository:  bosh/os-image-stemcell-builder }

      inputs:

      - name: bosh-repo

      - name: stemcell-build

      run:

        path: stemcell-build/script/build.sh
